plugins {
    id 'com.gradleup.shadow'
}

architectury {
    platformSetupLoomIde()
    fabric()
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common

    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}

dependencies {
    //Dependencies
    modImplementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"
    modImplementation "net.fabricmc.fabric-api:fabric-api:$rootProject.fabric_api_version"
    modImplementation "com.tterrag.registrate_fabric:Registrate-Fabric:$rootProject.registrate_refabricated"
    //modCompileOnly "com.simibubi.create:create-fabric:$rootProject.create_fabric"
    //   DEV NOTE: have Create Fabric in your mods folder instead - Arch Loom isn't remapping correctly
    modCompileOnly "com.simibubi.create:create-fucked-up-1.21.1:$rootProject.create_fabric"
    modImplementation "net.createmod.ponder:Ponder-Fabric-1.21.1:$rootProject.ponder"
    modImplementation "dev.engine-room.flywheel:flywheel-fabric-1.21.1:$rootProject.flywheel"

    //Mods for testing
    modRuntimeOnly "com.terraformersmc:modmenu:${rootProject.modmenu_version}"
    modRuntimeOnly "mezz.jei:jei-1.21.1-fabric:${rootProject.jei_version}"

    //Architectury
    common(project(path: ':common', configuration: 'namedElements')) { transitive = false }
    shadowBundle project(path: ':common', configuration: 'transformProductionFabric')
}

processResources {
    inputs.property 'mod_version', project.mod_version

    filesMatching('fabric.mod.json') {
        expand mod_version: inputs.properties.mod_version
    }
}

shadowJar {
    configurations = [project.configurations.shadowBundle]
    archiveClassifier = 'dev-shadow'
}

remapJar {
    inputFile.set shadowJar.archiveFile
}
