org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
dev_builds = false

# Totem Factory
mod_version = 1.1.2
create_fabric = 6.0.8.1+build.1744-mc1.20.1
create_forge = 6.0.8-290
registrate_refabricated = 1.3.79-MC1.20.1
registrate = MC1.20-1.3.3
jei_version = 15.20.0.127
modmenu_version = 7.2.2

# Project
archives_name = TotemFactory
maven_group = marcos.lumynitystudios.totemfactory
enabled_platforms = fabric,forge

minecraft_version = 1.20.1
fabric_loader_version = 0.17.3
fabric_api_version = 0.92.6+1.20.1
    # NeoForge 1.20.1 is based off of Forge 47.1.47
forge_version = 1.20.1-47.1.47

# Dumb shit Forge wants to work
ponder = 1.0.92
flywheel = 1.0.6-beta-269
mixinextras_version = 0.5.0