org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Totem Factory
mod_version = 1.1.0
create_fabric = no_file
create_forge = 6.0.8-290 //to update
registrate_refabricated = 1.3.79-MC1.20.1 //to update
registrate = MC1.20-1.3.3 //to update
jei_version = 19.27.0.336
modmenu_version = 11.0.3

# Project
archives_name = TotemFactory
maven_group = marcos.mysticcreationsteam.totemfactory
enabled_platforms = fabric,neoforge

minecraft_version = 1.21.1
fabric_loader_version = 0.18.0
fabric_api_version = 0.110.0.2+1.21.1
neoforge_version = 21.1.210

# Dumb shit Forge wants to work
ponder = 1.0.92 //to update
flywheel = 1.0.6-beta-269 //to update
mixinextras_version = 0.5.0